### PR TITLE
John tutorial pull request

### PR DESCRIPTION
**Pull request by jtcomp**

### CODE REVIEW

**Comment by elsevers** [comment]
There are a couple problems with your tutorial attempt, outlined below. Please try again.

- Commits 0e348ce, 05bade1, a3ccf03 are written in past tense instead of imperative present tense. See [here](https://github.com/Severson-Group/severson_group_git#sub_commit_msg)
- Your pull request is adding a new file `source/lipsum_insanity.txt.orig` that does not belong in the repository.

**Comment by jtcomp** [comment]
Disregard, I need to rebase my branch to account for Yunlei's merge

**Comment by elsevers** [comment]
Looks good, `TheBigK1d`. Please resolve the merge conflicts and then I'll merge you in. (You can do this by merging develop into your branch).

**Comment by elsevers** [comment]
Success!

**Pull request merged**
