### PR TITLE
Jason tutorial

### PR DESCRIPTION
**Pull request by jjsylvestre**

### CODE REVIEW

**Comment by elsevers** [comment]
It looks like you have't completed the tutorial yet. However, I am noticing a problem with commit a52954a (It looks like you have committed changes to line 5 as well as line 1).

**Comment by jjsylvestre** [comment]
What am I missing from the tutorial? I thought I completed it. 

I'm not sure why that commit deleted line 5. How would you like me to go about correcting that? Or what course of action would you like me to take?

**Comment by elsevers** [comment]
It appears to be missing steps 21 - 29. 

As for taking corrective action: 

1. you can checkout the commit before things went wrong and resume from there, or
1. you can start over (if you start over, you can try to get fancy and cherry pick individual commits that were successful from your current attempt to speed you up).

**Comment by jjsylvestre** [comment]
I started the tutorial over and created a separate pull request called 'jason_tutorial2'

**Comment by elsevers** [comment]
Okay, I will close this pull request then.

**Pull request closed without merging**
