### PR TITLE
Nishanth_tutorial

### PR DESCRIPTION
**Pull request by ngadiyar93**
Completed tutorial.

### CODE REVIEW

**Comment by elsevers** [comment]
@ngadiyar93 There are problems in the following commits:
1. _Commit ID d60904d:_ These changes were supposed to be committed in two separate commits, by staging one hunk of the file at a time.
2. _Commit ID 78083dc:_ The merge conflict was not resolved properly. The merge conflict identifiers `>>>>>>>` and `<<<<<<<` were committed into the repository.
3. _Commit ID 2d66204:_ Insufficient commit message.

Please try again. If you get stuck, reach out to @npetersen2.

**Comment by ngadiyar93** [comment]
@elsevers  I tried did it all over again. Please let me know how it looks.

**Comment by elsevers** [comment]
I am not sure what happened, but somehow your branch is now based off of `master` instead of develop. Specifically, see commit ID c524770. Try again.

**Comment by elsevers** [comment]
Merging this will create a mess in the repository history. Try again.

The reason that you couldn't push your new branch into the server was that a `Nishanth_tutorial` branch already existed and was pointing to a different commit. You would need to first delete `Nishanth_tutorial` from the server and then push up the new branch.

**Pull request closed without merging**
