### PR TITLE
federico_tutorial updates to develop branch for new group member. commit message length < 72 characters.

### PR DESCRIPTION
**Pull request by fedcoppo**
Completion of github tutorial for Severson group.

Performed actions include:
- Modify the lipsum_insanity.txt file to practice merge and commit operations, as well as file conflict resolution, including hunk staging.
- Ultimately, restore lipsum_insanity.txt file to its original state by checking it out of the develop branch.
- Append current user full name to end of users.txt file.

### CODE REVIEW

**Review by elsevers — CHANGES_REQUESTED** [review]
@fedcoppo, nice job. However, several of your commit messages have a line length that is over 72 characters. See guidelines [here](https://github.com/Severson-Group/severson_group_git#1ii-proper-commit-messages).

Please revise your tutorial (I recommend that you do it again from scratch) to fix this.

**Comment by fedcoppo** [comment]
Will repeat and correct.

Thanks,
Federico

**Comment by fedcoppo** [comment]
Completion of github tutorial for Severson group.

Performed actions include:

Modify the lipsum_insanity.txt file to practice merge and commit operations, as well as file conflict resolution, including hunk staging.
Ultimately, restore lipsum_insanity.txt file to its original state by checking it out of the develop branch.
Append current user full name to end of users.txt file.

Commit messages below 72 characters.

**Review by elsevers — CHANGES_REQUESTED** [review]
Close! However, it looks like in your last commit, you merged in your old branch that had the problematic commit messages. We don't want to merge those into the repo. Can you fix this?

image

**Pull request closed without merging**
