### PR TITLE
Takahiro turorial

### PR DESCRIPTION
**Pull request by noguchi-takahiro**
Complete my tutorial by following no. 1 through 27.

### CODE REVIEW

**Review by elsevers — CHANGES_REQUESTED** [review]
Hello @noguchi-takahiro, this is very close! But there is one problem that needs to be fixed before this PR can be merged: the `.gitignore` file is currently being modified by your PR, but it should not be modified:
Screen Shot 2022-09-26 at 12 46 54 PM

**Comment by noguchi-takahiro** [comment]
@elsevers, I fixed the problem by reverting to the .gitignore file. Could you review it again?

**Comment by noguchi-takahiro** [comment]
@elsevers, I fixed the problem by reverting to the .gitignore file. Could you review it again?

**Review by elsevers — CHANGES_REQUESTED** [review]
Hello @noguchi-takahiro, your `Files changed` tab now looks great. However, now the repository commit history doesn't match the steps for the tutorial. Since others use the past commits as an example of how to do the tutorial, I am pretty picky about this looking correct before approving a PR.
image
Please go ahead and fix this. You can get fancy and try to resolve it using `git rebase` or `git cherrypick`, but it may be simpler just to delete your branch and start over.

**Pull request closed without merging**
