### PR TITLE
Abhipriya tutorial

### PR DESCRIPTION
**Pull request by abhipriyabansal**
Added new content to lipsum_insanity.txt, resolved the merge conflicts, added a character name to users.txt.

### CODE REVIEW

**Review by npetersen2 — COMMENTED** [review]
Looks good to me.

@elsevers can you please review? thanks!

**Review by elsevers — APPROVED** [review]
Nice job @abhipriyabansal. This looks correct to me. Go ahead and merge.

**Comment by abhipriyabansal** [comment]
@elsevers it seems like I'm not authorized to merge it, can you check it once?

**Comment by elsevers** [comment]
Hmm, interesting. It looks to me like you have permissions to do this. Just to confirm, are you trying your merge within GitHub by pressing the button in this screenshot below:

image

**Comment by abhipriyabansal** [comment]
Yes, I am trying to merge using the button below but it is blocked.
Screen Shot 2023-08-01 at 1 45 41 PM

**Pull request merged**
