### PR TITLE
# Adonai_Tutorial

### PR DESCRIPTION
**Pull request by Adonay4**
This PR Adds *Anthony Stark* aka **Iron Man** to users.txt.

### CODE REVIEW

**Review by elsevers — CHANGES_REQUESTED** [review]
Nicely done! This is ready to merge -- except that now we have a merge conflict.

Please resolve the merge conflict in GitHub: 
image

Then re-request my review and I will approve.

**Comment by Adonay4** [comment]
Thanks Prof, I think we are good to go now.

**Review by elsevers — APPROVED** [review]
Looks great! Thanks @Adonay4. Please go ahead and merge.

**Comment by Adonay4** [comment]
Merge Adonai_Tutorial with develop

**Comment by Adonay4** [comment]
Should I go ahead and delete the Adonai_Tutorial branch?

**Pull request merged**
